# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47c9294d8eec9d038a6382ea409022a39e3bfe2b2cfa4247f2ee26a6a4b19f01aa89ff462674d93133228c1d5a8d31988a5f06d2e6b9207717d463cdf7ae43af

test:
  secret_key_base: 84694981a6ba6060569819e4ad8330d246aff30b2fa4ffa089411ce3c90914a1bb1d0e41910a2add834a143b02bfbef7b1fdafabd41aae58f46fa9e6e6804bf2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base:  2f2f103b98cad8140384acc9a2d6bef681f12f5a1d03a97d49b23625c7269fc5f6c615ac783a24dd0b56840aab0b72f4f7717b8d319e89a65e774650cc86bc9d

